--------------------------------------------------------
--  File created - Saturday-June-24-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "HOMESTAY"."BOOKING" 
   (	"CHECKINDATE" DATE DEFAULT sysdate, 
	"CHECKOUTDATE" DATE DEFAULT sysdate, 
	"NUMADULTS" NUMBER(*,0), 
	"NUMCHILDREN" NUMBER(*,0), 
	"DEPOSITAMOUNT" NUMBER(*,0), 
	"BILL" NUMBER(*,0), 
	"STAFFID" NUMBER(*,0), 
	"HOMESTAYID" NUMBER(*,0), 
	"BOOKINGID" NUMBER(*,0), 
	"GUESTID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOMESTAY.BOOKING
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOMESTAY"."PK1" ON "HOMESTAY"."BOOKING" ("BOOKINGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "HOMESTAY"."BOOKING" ADD CONSTRAINT "PK1" PRIMARY KEY ("BOOKINGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "HOMESTAY"."BOOKING" ADD CONSTRAINT "FK1" FOREIGN KEY ("HOMESTAYID")
	  REFERENCES "HOMESTAY"."HOMESTAY" ("HOMESTAYID") ENABLE;
  ALTER TABLE "HOMESTAY"."BOOKING" ADD CONSTRAINT "FK2" FOREIGN KEY ("GUESTID")
	  REFERENCES "HOMESTAY"."GUEST" ("GUESTID") ENABLE;
  ALTER TABLE "HOMESTAY"."BOOKING" ADD CONSTRAINT "STAFFID_FK" FOREIGN KEY ("STAFFID")
	  REFERENCES "HOMESTAY"."STAFF" ("STAFFID") ENABLE;
