--------------------------------------------------------
--  File created - Thursday-July-13-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FULLTIME
--------------------------------------------------------

  CREATE TABLE "HOMESTAY"."FULLTIME" 
   (	"FULLTIMESALARY" NUMBER(*,0), 
	"FULLSHIFT" NUMBER(*,0), 
	"STAFFID" NUMBER(*,0), 
	"FULLTIMEID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOMESTAY.FULLTIME
SET DEFINE OFF;
Insert into HOMESTAY.FULLTIME (FULLTIMESALARY,FULLSHIFT,STAFFID,FULLTIMEID) values (2200,12,4,2);
Insert into HOMESTAY.FULLTIME (FULLTIMESALARY,FULLSHIFT,STAFFID,FULLTIMEID) values (2200,12,7,3);
--------------------------------------------------------
--  DDL for Index FULLTIMEID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOMESTAY"."FULLTIMEID" ON "HOMESTAY"."FULLTIME" ("FULLTIMEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FULLTIME
--------------------------------------------------------

  ALTER TABLE "HOMESTAY"."FULLTIME" ADD CONSTRAINT "FULLTIMEID" PRIMARY KEY ("FULLTIMEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOMESTAY"."FULLTIME" MODIFY ("FULLTIMEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FULLTIME
--------------------------------------------------------

  ALTER TABLE "HOMESTAY"."FULLTIME" ADD CONSTRAINT "FK" FOREIGN KEY ("STAFFID")
	  REFERENCES "HOMESTAY"."STAFF" ("STAFFID") ENABLE;
