--------------------------------------------------------
--  File created - Saturday-June-24-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOMESTAY
--------------------------------------------------------

  CREATE TABLE "HOMESTAY"."HOMESTAY" 
   (	"HOMESTAYID" NUMBER(*,0), 
	"HOMESTAYNAME" VARCHAR2(500 BYTE), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"OFFICENO" VARCHAR2(100 BYTE), 
	"RENTPRICE" NUMBER(*,0), 
	"STAFFID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOMESTAY.HOMESTAY
SET DEFINE OFF;
Insert into HOMESTAY.HOMESTAY (HOMESTAYID,HOMESTAYNAME,ADDRESS,OFFICENO,RENTPRICE,STAFFID) values (1,'Twin Villa Homestay','Jalan Badik 11/4, Shah Alam, Selangor, Malaysia','03-421-2098',500,null);
--------------------------------------------------------
--  DDL for Index BOOKINGID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOMESTAY"."BOOKINGID_PK" ON "HOMESTAY"."HOMESTAY" ("HOMESTAYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table HOMESTAY
--------------------------------------------------------

  ALTER TABLE "HOMESTAY"."HOMESTAY" ADD CONSTRAINT "BOOKINGID_PK" PRIMARY KEY ("HOMESTAYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOMESTAY"."HOMESTAY" MODIFY ("OFFICENO" CONSTRAINT "OFFICENO_NN" NOT NULL ENABLE);
  ALTER TABLE "HOMESTAY"."HOMESTAY" MODIFY ("HOMESTAYNAME" CONSTRAINT "HOMESTAYNAME_NN" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HOMESTAY
--------------------------------------------------------

  ALTER TABLE "HOMESTAY"."HOMESTAY" ADD CONSTRAINT "FK5" FOREIGN KEY ("STAFFID")
	  REFERENCES "HOMESTAY"."STAFF" ("STAFFID") ENABLE;
