--------------------------------------------------------
--  File created - Thursday-July-06-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAINTENANCE
--------------------------------------------------------

  CREATE TABLE "HOMESTAY"."MAINTENANCE" 
   (	"MAINID" NUMBER(*,0), 
	"MAINNAME" VARCHAR2(500 BYTE), 
	"MAINPAYMENT" NUMBER(*,0), 
	"MAINDESC" VARCHAR2(500 BYTE), 
	"MAINDATE" DATE DEFAULT sysdate, 
	"MAINSTATUS" VARCHAR2(100 BYTE), 
	"TECHID" NUMBER(*,0), 
	"HOMESTAYID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOMESTAY.MAINTENANCE
SET DEFINE OFF;
Insert into HOMESTAY.MAINTENANCE (MAINID,MAINNAME,MAINPAYMENT,MAINDESC,MAINDATE,MAINSTATUS,TECHID,HOMESTAYID) values (1,'Preventive Maintenance',300,'Homestay cleaning',to_date('08/04/2023','DD/MM/RRRR'),'Completed',2,null);
Insert into HOMESTAY.MAINTENANCE (MAINID,MAINNAME,MAINPAYMENT,MAINDESC,MAINDATE,MAINSTATUS,TECHID,HOMESTAYID) values (2,'Corrective Maintenance',600,'Homestay repair',to_date('24/05/2023','DD/MM/RRRR'),'On Hold',3,null);
Insert into HOMESTAY.MAINTENANCE (MAINID,MAINNAME,MAINPAYMENT,MAINDESC,MAINDATE,MAINSTATUS,TECHID,HOMESTAYID) values (3,'Condition-based Maintenance',1000,'Facilities maintenance',to_date('21/02/2023','DD/MM/RRRR'),'Pending',4,null);
--------------------------------------------------------
--  DDL for Index MAINID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOMESTAY"."MAINID_PK" ON "HOMESTAY"."MAINTENANCE" ("MAINID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MAINTENANCE
--------------------------------------------------------

  ALTER TABLE "HOMESTAY"."MAINTENANCE" ADD CONSTRAINT "MAINID_PK" PRIMARY KEY ("MAINID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOMESTAY"."MAINTENANCE" MODIFY ("MAINNAME" CONSTRAINT "MAINNAME_NN" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MAINTENANCE
--------------------------------------------------------

  ALTER TABLE "HOMESTAY"."MAINTENANCE" ADD CONSTRAINT "HOMESTAYID_FK" FOREIGN KEY ("HOMESTAYID")
	  REFERENCES "HOMESTAY"."HOMESTAY" ("HOMESTAYID") ENABLE;
  ALTER TABLE "HOMESTAY"."MAINTENANCE" ADD CONSTRAINT "TECHID_FK" FOREIGN KEY ("TECHID")
	  REFERENCES "HOMESTAY"."TECHNICIAN" ("TECHID") ENABLE;
