--------------------------------------------------------
--  File created - Saturday-June-24-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TECHNICIAN
--------------------------------------------------------

  CREATE TABLE "HOMESTAY"."TECHNICIAN" 
   (	"TECHID" NUMBER(*,0), 
	"TECHNAME" VARCHAR2(500 BYTE), 
	"TECHNO" VARCHAR2(100 BYTE), 
	"TECHFIELD" VARCHAR2(500 BYTE), 
	"STAFFID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOMESTAY.TECHNICIAN
SET DEFINE OFF;
Insert into HOMESTAY.TECHNICIAN (TECHID,TECHNAME,TECHNO,TECHFIELD,STAFFID) values (2,'Masitah Shira','0193249683','Plumber',null);
Insert into HOMESTAY.TECHNICIAN (TECHID,TECHNAME,TECHNO,TECHFIELD,STAFFID) values (3,'Ahmad Azim','0104926583','Electrician',null);
Insert into HOMESTAY.TECHNICIAN (TECHID,TECHNAME,TECHNO,TECHFIELD,STAFFID) values (4,'Muhammad Hazim','0169992380','Computer technician',null);
--------------------------------------------------------
--  DDL for Index TECHID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOMESTAY"."TECHID_PK" ON "HOMESTAY"."TECHNICIAN" ("TECHID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TECHNICIAN
--------------------------------------------------------

  ALTER TABLE "HOMESTAY"."TECHNICIAN" ADD CONSTRAINT "TECHID_PK" PRIMARY KEY ("TECHID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOMESTAY"."TECHNICIAN" MODIFY ("TECHNO" CONSTRAINT "TECHNO_NN" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TECHNICIAN
--------------------------------------------------------

  ALTER TABLE "HOMESTAY"."TECHNICIAN" ADD CONSTRAINT "FK4" FOREIGN KEY ("STAFFID")
	  REFERENCES "HOMESTAY"."STAFF" ("STAFFID") ENABLE;
